<?xml version="1.0" encoding="utf-8"?><Database Name="QLBANAO" Class="QuanLyAoKhoacDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=LAPTOP-QN;Initial Catalog=QLBANAO;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="QLBANAOConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.CauHinh" Member="CauHinhs">
    <Type Name="CauHinh">
      <Column Name="IdCauHinh" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenBien" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GiaTri" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ChiTiet" Member="ChiTiets">
    <Type Name="ChiTiet">
      <Column Name="MaCt" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="HinhAnhSmall" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="MaSp" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.DanhMucSP" Member="DanhMucSPs">
    <Type Name="DanhMucSP">
      <Column Name="MaDm" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenDm" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="TrangThai" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ViTri" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="DanhMucSP_SanPham" Member="SanPhams" ThisKey="MaDm" OtherKey="MaDm" Type="SanPham" />
    </Type>
  </Table>
  <Table Name="dbo.DatHang" Member="DatHangs">
    <Type Name="DatHang">
      <Column Name="IDDatHang" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaHang" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Soluong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TenKhach" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="SoDT" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Size" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="TinhTrang" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Notes" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.LienHe" Member="LienHes">
    <Type Name="LienHe">
      <Column Name="IDLienHe" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaHang" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="TenKhach" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="SoDT" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NgayLienHe" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SanPham" Member="SanPhams">
    <Type Name="SanPham">
      <Column Name="MaSp" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenSp" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="MaSo" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="TenCt" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Gia" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="GiaNiemYet" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TrangThai" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HinhAnh" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Color" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Size" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="MoTaChiTiet" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="UuDai" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="MaDm" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="XuHuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="DanhMucSP_SanPham" Member="DanhMucSP" ThisKey="MaDm" OtherKey="MaDm" Type="DanhMucSP" IsForeignKey="true" />
    </Type>
  </Table>
</Database>